### Test single svd using NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[3,1,2],[5,8,1]])
b = np.array([5,10,15])
u,s,vT = np.linalg.svd(a, full_matrices=False)
s_eye = np.eye(s.shape[0])*s

In [3]:
# Check if 1/s is different from np.linalg.pinv
sigma_rec = 1/s
sigma_inv = np.eye(s.shape[0])*(sigma_rec*sigma_rec)
print(sigma_inv)
print(np.linalg.pinv(s_eye.T@s_eye))

[[0.00952296 0.         0.        ]
 [0.         0.09994002 0.        ]
 [0.         0.         0.33505232]]
[[0.00952296 0.         0.        ]
 [0.         0.09994002 0.        ]
 [0.         0.         0.33505232]]


In [4]:
x = vT.T@sigma_inv@s_eye.T@u.T@b
print(f"Calculated Solution: a:{x[0]:.4f} b:{x[1]:.4f} c:{x[2]:.4f}")
print(f"Actual Solution:     a:{20/7:.4f} b:{0:.4f} c:{5/7:.4f}")

Calculated Solution: a:2.8571 b:0.0000 c:0.7143
Actual Solution:     a:2.8571 b:0.0000 c:0.7143


### Test multiplying with singular matrix instead of using np.eye

In [104]:
a = np.array([[1,2,3],[3,1,2],[5,8,1]])
b = np.array([5,10,15])
u,s,vT = np.linalg.svd(a, full_matrices=False)
sigma_rec = 1/s
x = (vT.T*sigma_rec)@u.T@b
print(f"Singular Values: {np.round(s,4)}")
print(f"Singular Inverse Values: {np.round(sigma_rec,4)}")
print(f"Calculated Solution: {np.round(x,4)}")

Singular Values: [10.2474  3.1632  1.7276]
Singular Inverse Values: [0.0976 0.3161 0.5788]
Calculated Solution: [ 2.8571 -0.      0.7143]


### Solve multiple eqns in 3D using NumPy

In [130]:
# Get value for second set of equations so we can verify later
a = np.array([[1,4,3],[2,1,2],[1,8,1]])
b = np.array([2,3,10])
u,s,vT = np.linalg.svd(a, full_matrices=False)
sigma_rec = 1/s
x = vT.T*sigma_rec
x = x@u.T
x = x@b
print(f"Singular Values: {np.round(s,4)}")
print(f"Calculated Solution: {np.round(x,4)}")

Singular Values: [9.5133 3.0732 1.0261]
Calculated Solution: [ 2.6667  1.1333 -1.7333]


In [131]:
# Run SVD on 3D Array
a = np.array([[[1,2,3],[3,1,2],[5,8,1]],[[1,4,3],[2,1,2],[1,8,1]]])
b = np.array([[5,10,15],[2,3,10]])
#print(a.shape,b.shape)
u,s,vT = np.linalg.svd(a, full_matrices=False)
sigma_rec = 1/s.reshape(2,1,3)
x = vT.transpose(0,2,1)*sigma_rec
x = x@u.transpose(0,2,1)
x = x@b.reshape(2,3,1)
print(f"Singular Values: {np.round(s,4)}")
print(f"Calculated Solution: {np.round(x,4)}")

Singular Values: [[10.2474  3.1632  1.7276]
 [ 9.5133  3.0732  1.0261]]
Calculated Solution: [[[ 2.8571]
  [-0.    ]
  [ 0.7143]]

 [[ 2.6667]
  [ 1.1333]
  [-1.7333]]]


In [144]:
print(a.shape,u.shape,s.shape,vT.shape)

(5, 4) (5, 4) (4,) (4, 4)


In [147]:
z = a.T @ u[:,0]
print(z)

[-7.66823861 -7.53866471 -2.66634807 20.89684907]


In [148]:
(vT.T@sigma_inv@s_eye.T@u.T).shape

(4, 5)

In [17]:
import torch
a = torch.Tensor([[1,2,3,-4],[3,1,2,-9],[5,8,1,-14],[0,0,0,1],[5,2,1,-12]])
b = torch.Tensor([1,1,1,1,1])
u,s,vT = torch.linalg.svd(a, full_matrices=False)
s_eye = torch.eye(s.shape[0])*s
a_recon = u@s_eye@vT
print(a_recon)
sigma_rec = 1/s
sigma_inv = torch.eye(s.shape[0])*(sigma_rec*sigma_rec)
x = vT.T@sigma_inv@s_eye.T@u.T@b
print(f"Singular Values: {np.round(s,4)}")
print(f"Calculated Solution: {np.round(x,4)}")

tensor([[ 1.0000e+00,  2.0000e+00,  3.0000e+00, -4.0000e+00],
        [ 3.0000e+00,  1.0000e+00,  2.0000e+00, -9.0000e+00],
        [ 5.0000e+00,  8.0000e+00,  1.0000e+00, -1.4000e+01],
        [ 1.3847e-09,  4.2152e-07, -2.4310e-07,  1.0000e+00],
        [ 5.0000e+00,  2.0000e+00,  1.0000e+00, -1.2000e+01]])
Singular Values: tensor([23.6521,  4.2748,  2.8290,  0.5494])
Calculated Solution: tensor([1.2766, 0.1111, 0.5533, 0.4921])


In [97]:
x1 = np.array([[[1,2,3],[1,2,3],[1,2,3]],[[2,2,2],[2,2,2],[2,2,2]]])
x2 = np.array([[1,2,3],[3,3,3]])
x2 = x2.reshape(2,3,1)
print(x1.shape,x2.shape,(x1@x2).shape)
#print(x1*x2)
#print(x1[0]*x2[0])
print(x1.transpose(0,2,1)*x2)
print(x1[0].T*x2[0])

(2, 3, 3) (2, 3, 1) (2, 3, 1)
[[[1 1 1]
  [4 4 4]
  [9 9 9]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]]]
[[1 1 1]
 [4 4 4]
 [9 9 9]]


In [127]:
print(sigma_rec)
print(sigma_rec.reshape(3,1))

[0.10511625 0.32539221 0.97454458]
[[0.10511625]
 [0.32539221]
 [0.97454458]]
